### ISSUE TITLE
Conflict with Rich Text editor

### ISSUE THREAD

**Issue by darmeth** [osclass/plugin-item-success#2]
I'm using V3.5.2 with Modern. When posting a new listing, with Rich Text Editor plugin for my description, I still get the success page and all is well. Except all the text formatting from the listing description has been removed.

If I go to edit the listing, the formatting sticks because there is no item success call on edit, only on a new post.

Uninstalling Item Success resolves my problem with Rich Text plugin.

**Comment by garciademarina** [comment]
You items are validated once is created by the user?

You will only share validated items, because listing page must be accessible for the social networks.

**Comment by darmeth** [comment]
Hi, No issues with the validation - the listing is published and it appears on the site. I can share it to the social networks, no problem. Only the formatted text from Rich Text is removed from the description. So, if I have colour, underline, bold, <ul><li><p><span> etc, everything is removed and the text becomes plain text.

**Comment by garciademarina** [comment]
should be fixed on v1.1.10
