### ISSUE TITLE
Item link incomplete in social pop-up

### ISSUE THREAD

**Issue by tabuausada** [osclass/plugin-item-success#3]
I'm using OSC v3.4.3. After clicking share button item link doesn't show in pop-up window properly.

Instead of showing something like:  http://www.mysite.com/sitebr/index.php?page=item&id=456

It shows: http://www.mysite.com/sitebr/index.php?page=item

So if we post link like this its just sends the audience to the 404 page...

Please see following thread for more detail: http://forums.osclass.org/plugins-20/item-success-plugin-not-working-properly-item-link-incomplete-in-social-pop-up/

**Comment by garciademarina** [comment]
should be fixed on v1.1.10
